version: '3.8'

services:
  authservice:
    build:
      context: .
      dockerfile: AuthService/AuthService.API/Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_AUDIENCE=${JWT_AUDIENCE}
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}

  bookingservice:
    build:
      context: .
      dockerfile: BookingService/BookingService.API/Dockerfile
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  movieservice:
    build:
      context: .
      dockerfile: MovieService/MovieService.API/Dockerfile
    ports:
      - "5003:8080"

  showtimeservice:
    build:
      context: .
      dockerfile: ShowtimeService/ShowtimeService.API/Dockerfile
    ports:
      - "5004:8080"

  pricingservice:
    build:
      context: .
      dockerfile: PricingService/PricingService.API/Dockerfile
    ports:
      - "5005:8080"


  userprofileservice:
    build:
      context: .
      dockerfile: UserProfileService/UserProfileService.API/Dockerfile
    ports:
      - "5006:8080"
